<!-- Svelte page auto generated by "gen-posts.py" -->
<title>Pwnzer0tt1 | Oscar Urselli</title>

<h2 class="ibm-plex-mono-semibold">Pwnzer0tt1</h2>
<p class="ibm-plex-mono-regular">Creation of a CTF team.</p>
<div class="ibm-plex-mono-regular"><p>After CyberChallenge I and the other members of the team decided to create a CTF team called <a href="https://pwnzer0tt1.it/">Pwnzer0tt1</a>.</p>

</div>

<div class="d-flex justify-content-between">
    {#if 3 > 0}
        <a href="/posts/cc-2022" class="btn btn-outline-secondary ibm-plex-mono-regular rounded-0">&lt&lt&lt Previous</a>
    {/if}
    {#if 3 < 10 - 1}
        <a href="/posts/itasec-2023" class="ms-auto btn btn-outline-secondary ibm-plex-mono-regular rounded-0">Next &gt;&gt;&gt;</a>
    {/if}
</div>        
