baseURL = 'https://oscarurselli.com/'
enableRobotsTXT = true
languageCode = 'en-us'
title = 'Oscar Urselli'
theme = "nightfall"


[menu]
    [[menu.header]]
        name = "posts"
        weight = 1
        url = "posts"
    [[menu.header]]
        name = "about"
        weight = 0
        url = "about"


[params]
user = "Oscar Urselli"
hostname = "oscarurselli.com"
sitedescription = 'A random website about a random person.'
published = false
    [params.author]
        name = "Oscar Urselli"
        email = "studio@oscarurselli.com"


[[params.social]]
key = 0
name = "github"
url = "https://github.com/oscar0urselli"
icon = "bi bi-github"
target = "_blank"
aria = "GitHub Profile"

[[params.social]]
key = 1
name = "instagram"
url = "https://www.instagram.com/oscarurselli"
icon = "bi bi-instagram"
target = "_blank"
aria = "Instagram Profile"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.linkedin.com/in/oscar-urselli-121a98294/"
icon = "bi bi-linkedin"
target = "_blank"
aria = "LinkedIn Profile"

[[params.social]]
key = 3
name = "email"
url = "mailto:studio@oscarurselli.com"
icon = "bi bi-envelope-paper-fill"
aria = "My e-Mail Address"