<!-- Svelte page auto generated by "gen-posts.py" -->
<title>Web Security tutor - Cyberchallenge 2025 | Oscar Urselli</title>

<h2 class="ibm-plex-mono-semibold">Web Security tutor - Cyberchallenge 2025</h2>
<p class="ibm-plex-mono-regular">Tutoring activity in web security for Cyberchallenge 2025 at Polytechnic of Bari.</p>
<div class="ibm-plex-mono-regular"><p>I participated as a tutor of Cyberchallenge.IT 2025. As the last edition I was responsible for the training in the category of web security.</p>

</div>

<div class="d-flex justify-content-between">
    {#if 9 > 0}
        <a href="/posts/cc-2024" class="btn btn-outline-secondary ibm-plex-mono-regular rounded-0">&lt&lt&lt Previous</a>
    {/if}
    {#if 9 < 10 - 1}
        <a href="/posts/None" class="ms-auto btn btn-outline-secondary ibm-plex-mono-regular rounded-0">Next &gt;&gt;&gt;</a>
    {/if}
</div>        
