<!-- Svelte page auto generated by "gen-posts.py" -->
<title>Web Security tutor - Cyberchallenge 2024 | Oscar Urselli</title>

<h2 class="ibm-plex-mono-semibold">Web Security tutor - Cyberchallenge 2024</h2>
<p class="ibm-plex-mono-regular">Tutoring activity in web security for Cyberchallenge 2024 at Polytechnic of Bari.</p>
<div class="ibm-plex-mono-regular"><p>In the 2024 edition of Cyberchallenge.IT i partecipated as a tutor and I held lessons about web security. With me there were also other memebers of Pwnzer0tt1 who trained participants on cryptography, software and network security.</p>

</div>

<div class="d-flex justify-content-between">
    {#if 8 > 0}
        <a href="/posts/poliba" class="btn btn-outline-secondary ibm-plex-mono-regular rounded-0">&lt&lt&lt Previous</a>
    {/if}
    {#if 8 < 10 - 1}
        <a href="/posts/cc-2025" class="ms-auto btn btn-outline-secondary ibm-plex-mono-regular rounded-0">Next &gt;&gt;&gt;</a>
    {/if}
</div>        
