<!-- Svelte page auto generated by "gen-posts.py" -->
<title>Cyberchallenge 2022 | Oscar Urselli</title>

<h2 class="ibm-plex-mono-semibold">Cyberchallenge 2022</h2>
<p class="ibm-plex-mono-regular">National competion of cybersecurity between universities.</p>
<div class="ibm-plex-mono-regular"><p>During the same period of the Olicyber, I also took part in <a href="https://cyberchallenge.it/halloffame/2022">this project for universities</a>. Here I passed the selections and entered the official team of the <a href="https://www.poliba.it/">Polytechnic of Bari</a> with other 5 students.</p>

</div>

<div class="d-flex justify-content-between">
    {#if 2 > 0}
        <a href="/posts/firegex" class="btn btn-outline-secondary ibm-plex-mono-regular rounded-0">&lt&lt&lt Previous</a>
    {/if}
    {#if 2 < 10 - 1}
        <a href="/posts/pwnzer0tt1" class="ms-auto btn btn-outline-secondary ibm-plex-mono-regular rounded-0">Next &gt;&gt;&gt;</a>
    {/if}
</div>        
