<!-- Svelte page auto generated by "gen-posts.py" -->
<title>Olicyber 2023 | Oscar Urselli</title>

<h2 class="ibm-plex-mono-semibold">Olicyber 2023</h2>
<p class="ibm-plex-mono-regular">Highschool Italian championship of cybersecurity.</p>
<div class="ibm-plex-mono-regular"><p>For the <a href="https://olicyber.it/edizioni/2023">second time</a>, I made it to the national finals and won the bronze medal.</p>

</div>

<div class="d-flex justify-content-between">
    {#if 6 > 0}
        <a href="/posts/liceo" class="btn btn-outline-secondary ibm-plex-mono-regular rounded-0">&lt&lt&lt Previous</a>
    {/if}
    {#if 6 < 10 - 1}
        <a href="/posts/poliba" class="ms-auto btn btn-outline-secondary ibm-plex-mono-regular rounded-0">Next &gt;&gt;&gt;</a>
    {/if}
</div>        
