<!-- Svelte page auto generated by "gen-posts.py" -->
<title>Itasec 2023 - 1st Highschool CTF Workshop | Oscar Urselli</title>

<h2 class="ibm-plex-mono-semibold">Itasec 2023 - 1st Highschool CTF Workshop</h2>
<p class="ibm-plex-mono-regular">A one day event for highschool students.</p>
<div class="ibm-plex-mono-regular"><p>I helped in the organization of a <a href="https://itasec.it/workshops/1st-highschools-ctf-workshop/">workshop</a> and a <a href="https://ctf.itasec.it/">CTF</a> for highschool students during ITASEC 2023. In particular, I and the members of <a href="https://pwnzer0tt1.it/">Pwnzer0tt1</a> and <a href="https://www.mntcrl.it/">M0NT3C4RL0</a> introduced the basics of cybersecurity. I covered the part related to OSINT.</p>

</div>

<div class="d-flex justify-content-between">
    {#if 4 > 0}
        <a href="/posts/pwnzer0tt1" class="btn btn-outline-secondary ibm-plex-mono-regular rounded-0">&lt&lt&lt Previous</a>
    {/if}
    {#if 4 < 10 - 1}
        <a href="/posts/liceo" class="ms-auto btn btn-outline-secondary ibm-plex-mono-regular rounded-0">Next &gt;&gt;&gt;</a>
    {/if}
</div>        
