<!-- Svelte page auto generated by "gen-posts.py" -->
<title>Olicyber 2022 | Oscar Urselli</title>

<h2 class="ibm-plex-mono-semibold">Olicyber 2022</h2>
<p class="ibm-plex-mono-regular">Highschool Italian championship of cybersecurity.</p>
<div class="ibm-plex-mono-regular"><p><a href="https://olicyber.it/edizioni/2022">This project</a> was my first encounter with cybersecurity. I managed to pass all the selections and won the bronze medal in the national finals.</p>

</div>

<div class="d-flex justify-content-between">
    {#if 0 > 0}
        <a href="/posts/None" class="btn btn-outline-secondary ibm-plex-mono-regular rounded-0">&lt&lt&lt Previous</a>
    {/if}
    {#if 0 < 10 - 1}
        <a href="/posts/firegex" class="ms-auto btn btn-outline-secondary ibm-plex-mono-regular rounded-0">Next &gt;&gt;&gt;</a>
    {/if}
</div>        
