<!-- Svelte page auto generated by "gen-posts.py" -->
<title>Firegex | Oscar Urselli</title>

<h2 class="ibm-plex-mono-semibold">Firegex</h2>
<p class="ibm-plex-mono-regular">Firewall for attack/defense CTFs</p>
<div class="ibm-plex-mono-regular"><p><em>Firegex is a firewall that includes different functionalities, created for CTF Attack-Defence competitions that has the aim to limit or totally deny malicious traffic through the use of different kind of filters.</em> More infos at this <a href="https://github.com/Pwnzer0tt1/firegex">page</a>...</p>
<p>Development started about 2 weeks before the final of <a href="https://cyberchallenge.it/attack-defense/2022">CyberChallenge.IT 2022</a>. At the beginning, the idea was of having a way to block potential payload from other players until we where able to patch the exploited vulnerabilities.</p>
<p>Now, the project has evolved and is capable of doing much more than simply dropping packet based on a set of regular expressions.</p>

</div>

<div class="d-flex justify-content-between">
    {#if 1 > 0}
        <a href="/posts/olicyber-2022" class="btn btn-outline-secondary ibm-plex-mono-regular rounded-0">&lt&lt&lt Previous</a>
    {/if}
    {#if 1 < 10 - 1}
        <a href="/posts/cc-2022" class="ms-auto btn btn-outline-secondary ibm-plex-mono-regular rounded-0">Next &gt;&gt;&gt;</a>
    {/if}
</div>        
