<!-- Svelte page auto generated by "gen-posts.py" -->
<title>Liceo G. Moscati | Oscar Urselli</title>

<h2 class="ibm-plex-mono-semibold">Liceo G. Moscati</h2>
<p class="ibm-plex-mono-regular">Graduation from highschool.</p>
<div class="ibm-plex-mono-regular"><p>Here I had a starting approach with C++, during the study I created some web sites for different projects. I also partecipated in various school competitions of chemistry, physics and mathematics.</p>

</div>

<div class="d-flex justify-content-between">
    {#if 5 > 0}
        <a href="/posts/itasec-2023" class="btn btn-outline-secondary ibm-plex-mono-regular rounded-0">&lt&lt&lt Previous</a>
    {/if}
    {#if 5 < 10 - 1}
        <a href="/posts/olicyber-2023" class="ms-auto btn btn-outline-secondary ibm-plex-mono-regular rounded-0">Next &gt;&gt;&gt;</a>
    {/if}
</div>        
