<!-- Svelte page auto generated by "gen-posts.py" -->
<title>Poliba | Oscar Urselli</title>

<h2 class="ibm-plex-mono-semibold">Poliba</h2>
<p class="ibm-plex-mono-regular">Computer engineering.</p>
<div class="ibm-plex-mono-regular"><p>I&#39;m currently an undergraduate in computer engineering at the <a href="https://www.poliba.it/">Polytechnic of Bari</a>.</p>

</div>

<div class="d-flex justify-content-between">
    {#if 7 > 0}
        <a href="/posts/olicyber-2023" class="btn btn-outline-secondary ibm-plex-mono-regular rounded-0">&lt&lt&lt Previous</a>
    {/if}
    {#if 7 < 10 - 1}
        <a href="/posts/cc-2024" class="ms-auto btn btn-outline-secondary ibm-plex-mono-regular rounded-0">Next &gt;&gt;&gt;</a>
    {/if}
</div>        
